### ISSUE TITLE
Chrome version not found

### ISSUE THREAD

**Issue by WildeKartoffel** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#2]
When I try to execute "chrome_d_download.py" the Chrome version I have on my pc cannot be found. My chrome version is "119.0.6045.106".
The latest available version I can find is "114.0.5735.90", searching on the website that you entered in the code: "https://chromedriver.storage.googleapis.com/?delimiter=/&prefix="

I really appriciate your work and want to thank you for your effort!

Best regards
WK

**Comment by Priyanshu-hawk** [comment]
Hello @WildeKartoffel 

I am using chrome with version (119.0.6045.105)
When you execute "chrome_d_download.py". it will download the latest chrome driver.

So in the code i've added a condition to check if the chrome version in the local system and chromedriver version available at the online repository are matched by prefix. If so then download the compatible version of chromedriver. 

**IMP**
start - Chromedriver 114.x.x.x : was the last release at https://chromedriver.chromium.org/downloads
Chromedriver 115.x.x.x - present : version come from different source - https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json

![image](https://github.com/Priyanshu-hawk/ChatGPT-unofficial-api-selenium/assets/76026651/bdc9469f-a12e-47d9-8b0c-0979700a8060)

So, if you manually want to download chromedriver. you can found it here - https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json (Its a JSON file open it in firefox or use some json beautifier otherwise it's a big mess 😮‍💨).

Best Wishes.

**Comment by WildeKartoffel** [comment]
Thanks a lot for the fast Response and detailed answer!

Best
WK
